# fly.toml app configuration file generated for sgsg-client on 2024-04-07T00:53:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sgsg-client'
primary_region = 'arn'

[build]

[env]
  AUTH_URI = 'sgsg-service-auth.fly.dev:3002'
  PROFILE_URI = 'sgsg-service-profile.fly.dev:3003'
  PUBLIC_AUTH_URL = 'https://sgsg-service-auth.fly.dev'
  TARGET = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
