export const Config = {
    VITE_API_URL: import.meta.env.VITE_API_URL as string,
    VITE_NODE_ENV: import.meta.env.VITE_NODE_ENV as string,
    VITE_DOMAIN_URL: import.meta.env.VITE_DOMAIN_URL as string,
    VITE_FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY as string,
    VITE_FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN as string,
    DAY_FORMAT: 'YYYY-MM-DD',
    MONTH_FORMAT: 'YYYY-MM',
    DAYTIME_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
    DAYTIME_FORMAT_SHORT: 'MM-DD HH:mm',
    STRING_MEDIUM: 200,
    STRING_LONG: 1000,
    MAX_FILE_SIZE: 10000000,
    USER_SESSION_EXPIRE_IN_HOURS: 24,
};
