export const Config = {
    DAY_FORMAT: 'YYYY-MM-DD',
    MONTH_FORMAT: 'YYYY-MM',
    DAYTIME_FORMAT: 'YYYY-MM-DDTHH:mm:ss',
    DAYTIME_FORMAT_SHORT: 'MM-DD HH:mm',
    STRING_MEDIUM: 200,
    STRING_LONG: 1000,
    MAX_FILE_SIZE: 10000000,
    USER_SESSION_EXPIRE_IN_HOURS: 24,
};
