FROM golang:1.19

WORKDIR /usr/src

COPY ./server/go.sum ./
COPY ./server/go.mod ./
COPY ./server/grpc ./grpc
COPY ./server/service-users ./service-users

RUN go mod tidy
RUN go build -v -o /usr/local/bin/app ./service-users/...
COPY ./server/service-users/migrations /usr/local/bin/migrations

CMD ["app"]
