version: "3"
services:
  client:
    container_name: sgsg-client
    working_dir: /client
    build:
      context: ./client
      target: prod
      args:
        ENV: production
        PUBLIC_SERVER_HTTP: https://api-sgsg.bearbyte.org
        SERVER_HTTP: https://api-sgsg.bearbyte.org
        SERVER_GRPC: api-sgsg.bearbyte.org:8443
        COOKIE_DOMAIN: .bearbyte.org
        UPSEND_KEY: ${UPSEND_KEY}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    container_name: sgsg-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}
        loki-retries: "5"
        loki-batch-size: "400"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
