version: "3"
services:
  server:
    container_name: sgsg-server
    working_dir: /server
    build:
      context: ./server
      target: prod
    volumes:
      - ./server:/server
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      ENV: production
      HTTP_PORT: 8090
      GRPC_PORT: 8091
      CLIENT_URL: https://sgsg.bearbyte.org
      SERVER_HTTP: https://api-sgsg.bearbyte.org
      COOKIE_DOMAIN: .bearbyte.org
      CERT_PATH: /etc/letsencrypt/live/api-sgsg.bearbyte.org/fullchain.pem
      KEY_PATH: /etc/letsencrypt/live/api-sgsg.bearbyte.org/privkey.pem
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
    ports:
      - 443:8090
      - 8443:8091
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}
        loki-retries: "5"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
        loki-batch-size: "400"
