FROM golang:1.19

WORKDIR /usr/src

COPY ./server/go.sum ./
COPY ./server/go.mod ./
COPY ./server/grpc ./grpc
COPY ./server/gateway ./gateway

RUN go mod tidy
RUN go build -v -o /usr/local/bin/app ./gateway/...

CMD ["app"]
