version: "3"
services:
  client:
    container_name: sgsg-client
    working_dir: /client
    build:
      context: ./client
      target: prod
      args:
        - ENV=production
        - PUBLIC_SERVER_HTTP=https://api-sgsg.bearbyte.org
        - SERVER_HTTP=https://api-sgsg.bearbyte.org
        - SERVER_GRPC=api-sgsg.bearbyte.org:8443
        - COOKIE_DOMAIN=.bearbyte.org
        - UPSEND_KEY=${UPSEND_KEY}
    restart: unless-stopped

  nginx:
    container_name: sgsg-nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
