FROM golang:1.19

WORKDIR /usr/src

COPY ./go.sum ./
COPY ./go.mod ./
COPY ./server/service-email ./server/service-email

RUN go mod tidy
RUN go build -v -o /usr/local/bin/app ./server/service-email/...

CMD ["app"]
