FROM golang:1.19

WORKDIR /usr/src

COPY ./go.sum ./
COPY ./go.mod ./
COPY ./grpc ./grpc
COPY ./server/service-users ./server/service-users

RUN go mod tidy
RUN go build -v -o /usr/local/bin/app ./server/service-users/...
COPY ./server/service-users/migrations /migrations

CMD ["app"]
