FROM golang:1.19

WORKDIR /usr/src/app

COPY ./server/service-email/go.sum ./
COPY ./server/service-email/go.mod ./
RUN go mod download && go mod verify

COPY ./server/service-email ./
RUN go build -v -o /usr/local/bin/app ./...

CMD ["app"]
