FROM golang:1.19

WORKDIR /usr/src

COPY ./go.sum ./
COPY ./go.mod ./
COPY ./proto ./proto
COPY ./server/service-files ./server/service-files

RUN go mod tidy
RUN go build -v -o /usr/local/bin/app ./server/service-files/...
COPY ./server/service-files/migrations /migrations

CMD ["app"]
