FROM golang:1.19

WORKDIR /usr/src

COPY ./go.sum ./
COPY ./go.mod ./
COPY ./proto ./proto
COPY ./server/service-notes ./server/service-notes

RUN go mod tidy
RUN go build -v -o /usr/local/bin/app ./server/service-notes/...
COPY ./server/service-notes/migrations /migrations

CMD ["app"]
