FROM golang:1.19

WORKDIR /usr/src/app

COPY ./server/gateway/go.sum /usr/src/app
COPY ./server/gateway/go.mod /usr/src/app
COPY ./server/gateway /usr/src/app
RUN go mod tidy
RUN go build -v -o /usr/local/bin ./...

CMD ["gateway"]
