name: Deploy

on:
  push:
    branches:
      - release

jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.yml
  deploy-client:
    needs: lint-client
    uses: ./.github/workflows/deploy-client.yml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  lint-service-auth:
    uses: ./.github/workflows/lint-service-auth.yml
  deploy-service-auth:
    needs: lint-service-auth
    uses: ./.github/workflows/deploy-service-auth.yml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  lint-service-profile:
    uses: ./.github/workflows/lint-service-profile.yml
  deploy-service-profile:
    needs: lint-service-profile
    uses: ./.github/workflows/deploy-service-profile.yml
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
