name: Deploy Client

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true
      CLIENT_IP: 
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config <<END
          Host prod
            HostName ${{ secrets.CLIENT_IP }}
            User mat
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
      - name: Check out the source
        run: ssh prod 'cd /home/mat/sgsg/ && git checkout release && git pull'

      - name: Stop the server
        run: ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.client.yml stop'

      - name: Start the server
        run: ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.client.yml up -d --build'
