name: Lint Client
on:
  workflow_call:

env:
  TARGET: production
  JWT_SECRET: JWT_SECRET
  PUBLIC_DIRECTUS_URL: https://template-directus.fly.dev
  PUBLIC_AUTH_URL: http://localhost:3001
  AUTH_URI: service-auth:3002
  PROFILE_URI: service-profile:3003

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm i
      - run: npm run check
      - run: npm run lint
      - run: npm run build
